[metadata]
description_file = README.md

[options]
#...
packages =
    peak_detection
    peak_detection.RangingModels
    peak_detection.RangingModels.RangingNN
    peak_detection.IonIdentificationModels
    peak_detection.IonIdentificationModels.Ionclassifier
    peak_detection.IonIdentificationModels.RF
